trigger:
- main

pool:
  name: APPSEALING

parameters:
- name: APPLE_ID
  type: string
  default: 'puzznic@inka.co.kr'
- name: APP_SPECIFIC_PASSWORD
  type: string
  default: 'qbrz-hmfz-robj-eohm'
- name: TEAM_ID
  type: string
  default: '22X77ENQ2H'
- name: PROVISIONING_PROFILE_NAME
  type: string
  default: 'AppSealing Wildcard Distribution Profile'

steps:
  - script: |
      # Define paths for provisioning profile and keychain setup
      P12_CERT_PATH="$(Build.SourcesDirectory)/ios/App/distribution.p12"
      PROVISIONING_PROFILE_PATH="$(Build.SourcesDirectory)/ios/App/profile.mobileprovision"
      KEYCHAIN_PATH="$HOME/Library/Keychains/temp-keychain.keychain-db"
      KEYCHAIN_PASSWORD="temp123"

      # Create a temporary keychain for code signing
      if security list-keychains | grep -q "temp-keychain.keychain-db"; then
          echo "Deleting existing temporary keychain..."
          security delete-keychain "$KEYCHAIN_PATH"
      fi

      echo "Creating temporary keychain..."
      security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

      echo "Setting temporary keychain as default..."
      security list-keychains -d user -s "$KEYCHAIN_PATH"
      security default-keychain -s "$KEYCHAIN_PATH"
      security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
      security set-keychain-settings -lut 3600 "$KEYCHAIN_PATH"

      echo "Importing distribution certificate (PKCS#12) into temporary keychain..."
      security import "$P12_CERT_PATH" -k "$KEYCHAIN_PATH" -P "123456" -T /usr/bin/codesign
      security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
    displayName: 'Setup Temporary Keychain and Install Certificate'

  - task: UseNode@1
    inputs:
      version: '20.x'
    displayName: 'Install Node.js 20'

  - script: |
      export PATH="$PATH:/usr/local/bin"
      echo "Node.js version: $(node -v)"
      echo "npm version: $(npm -v)"
    displayName: 'Verify Node.js Installation'

  - script: |
      echo "Installing Ionic CLI..."
      npm install -g @ionic/cli
      
      echo "Installing project dependencies..."
      npm ci
    displayName: 'Install Dependencies'

  - script: |
      echo "Regenerating iOS platform..."
      rm -rf ios/App
      
      ionic cap add ios
      
      echo "Syncing iOS platform..."
      ionic cap sync ios --force
      
      PBXPROJ_PATH="ios/App/App.xcodeproj/project.pbxproj"
      
      if [ ! -f "$PBXPROJ_PATH" ]; then
        echo "##vso[task.logissue type=error] pbxproj file not found!"
        exit 1
      fi
      
      # Set CODE_SIGN_STYLE to Automatic for all targets
      sed -i '' 's/CODE_SIGN_STYLE = Manual;/CODE_SIGN_STYLE = Automatic;/g' "$PBXPROJ_PATH"
      
      # Remove provisioning profile settings from Pods targets
      sed -i '' '/PROVISIONING_PROFILE_SPECIFIER/d' "$PBXPROJ_PATH"
      
      echo "Updated Xcode project for automatic signing."
    displayName: 'Update Xcode Project for Signing'

  - script: |
      cd ios/App
      
      pod install --repo-update
      
      if [ $? -ne 0 ]; then
        echo "##vso[task.logissue type=error] CocoaPods installation failed!"
        exit 1
      fi
      
      echo "CocoaPods dependencies installed successfully."
    displayName: 'Install Pods'
    
  - script: |
      IOS_PATH="ios/App"
      if [ -d "$IOS_PATH" ]; then
          APP_NAME=$(ls "$IOS_PATH" | grep ".xcodeproj" | sed 's/.xcodeproj//')
          if [ -z "$APP_NAME" ]; then
              echo "##vso[task.logissue type=error] Xcode project not found in iOS directory"
              exit 1
          fi
          echo "Detected app name: $APP_NAME"
      else
          echo "##vso[task.logissue type=error] iOS directory not found"
          exit 1
      fi
      echo "##vso[task.setvariable variable=APP_NAME]$APP_NAME"
    displayName: 'Detect App Name'

  - script: |
      echo "Extracting Bundle ID from pbxproj file..."
      
      PBXPROJ_PATH="ios/App/App.xcodeproj/project.pbxproj"
      
      if [ -f "$PBXPROJ_PATH" ]; then
          BUNDLE_ID=$(grep -A1 'PRODUCT_BUNDLE_IDENTIFIER' "$PBXPROJ_PATH" | grep -oE 'com\.[a-zA-Z0-9._-]+' | head -n 1)
          
          if [ -z "$BUNDLE_ID" ]; then
              echo "##vso[task.logissue type=error] Failed to extract Bundle ID from pbxproj file!"
              exit 1
          fi
          
          echo "Extracted BUNDLE_ID: $BUNDLE_ID"
          echo "##vso[task.setvariable variable=BUNDLE_ID]$BUNDLE_ID"
      else
          echo "##vso[task.logissue type=error] pbxproj file not found at $PBXPROJ_PATH!"
          exit 1
      fi
    displayName: 'Extract Bundle ID from pbxproj File'

  - script: |
      cd ios/App
      EXPORT_DIR="$(Build.ArtifactStagingDirectory)"
      ARCHIVE_PATH="$EXPORT_DIR/${APP_NAME}.xcarchive"

      echo "Archiving iOS project..."
      xcodebuild clean archive \
        -workspace "${APP_NAME}.xcworkspace" \
        -scheme "${APP_NAME}" \
        -sdk iphoneos \
        -configuration Release \
        CODE_SIGN_IDENTITY="Apple Distribution" \
        CODE_SIGN_STYLE="Manual" \
        DEVELOPMENT_TEAM="${{ parameters.TEAM_ID }}" \
        PROVISIONING_PROFILE_SPECIFIER="${{ parameters.PROVISIONING_PROFILE_NAME }}" \
        -archivePath "$ARCHIVE_PATH"
    displayName: 'Archive iOS App'

  - script: |
      EXPORT_DIR="$(Build.ArtifactStagingDirectory)"
      
      cat << EOF > "$EXPORT_DIR/ExportOptions.plist"
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
        <dict>
            <key>method</key>
            <string>app-store-connect</string>
            <key>teamID</key>
            <string>${{ parameters.TEAM_ID }}</string>
            <key>provisioningProfiles</key>
            <dict>
                <key>$BUNDLE_ID</key>
                <string>${{ parameters.PROVISIONING_PROFILE_NAME }}</string>
            </dict>
        </dict>
      </plist>
      EOF
      echo "Generated ExportOptions.plist:"
      cat "$EXPORT_DIR/ExportOptions.plist"
    displayName: 'Generate Export Options'

  - script: |
      EXPORT_DIR="$(Build.ArtifactStagingDirectory)"
      xcodebuild -exportArchive \
        -archivePath "$EXPORT_DIR/${APP_NAME}.xcarchive" \
        -exportOptionsPlist "$EXPORT_DIR/ExportOptions.plist" \
        -exportPath "$EXPORT_DIR"
    displayName: 'Export IPA'

  - script: |
      # Grant execution permission to generate_hash script
      HASH_SCRIPT_PATH="$(Build.SourcesDirectory)/ios/App/AppSealingSDK/Tools/generate_hash"
      IPA_PATH=$(find "$(Build.ArtifactStagingDirectory)" -type f -name "*.ipa" | head -n 1)

      echo "Granting execution permission to generate_hash..."
      chmod +x "$HASH_SCRIPT_PATH"

      echo "Running generate_hash with IPA... $IPA_PATH"
      "$HASH_SCRIPT_PATH" "$IPA_PATH"
    displayName: 'Run generate_hash on IPA'

  - script: |
      IPA_PATH=$(find "$(Build.ArtifactStagingDirectory)" -type f -name "*.ipa" | head -n 1)
      if [ ! -f "$IPA_PATH" ]; then
          echo "##vso[task.logissue type=error] IPA file not found!"
          exit 1
      fi
      xcrun altool --upload-app \
        --file "$IPA_PATH" \
        --type ios \
        --username "${{ parameters.APPLE_ID }}" \
        --password "${{ parameters.APP_SPECIFIC_PASSWORD }}"
    displayName: 'Upload to TestFlight'

  - script: |
      TEMP_KEYCHAIN_PATH="$HOME/Library/Keychains/temp-keychain.keychain-db"
      [ -f "$TEMP_KEYCHAIN_PATH" ] && security delete-keychain "$TEMP_KEYCHAIN_PATH"
      rm -rf platforms/ios/build
    displayName: 'Cleanup'
